# 这里放你的个人强制规则，优先级高于 Johnshall 上游规则。
# 示例：
# DOMAIN-SUFFIX,example.com,PROXY
# DOMAIN-SUFFIX,example.cn,DIRECT

# 常用检测网站，建议走代理，方便确认外网出口 IP
DOMAIN-SUFFIX,browserleaks.com,PROXY
DOMAIN-SUFFIX,ipleak.net,PROXY
DOMAIN-SUFFIX,dnsleaktest.com,PROXY
DOMAIN-SUFFIX,test-ipv6.com,PROXY
